site_name: FerrumAI

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Usage: usage.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            show_root_heading: true
            show_signature: true
            show_source: true

